[package]
name = "vte4-app1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.4", package = "gtk4" }
vte4 = { version = "0.1" }
glib = { version = "0.15" }
